---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab-ce
          image: gitlab/gitlab-ce:latest
          env:
            - name: EXTERNAL_URL
              value: http://gitlab.example.com
            - name: GITLAB_ROOT_PASSWORD
              value: cgsLMpJjfn10sLqsTiiFwOSjzfIcaxY3fMuln
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                gitlab_rails['allowed_hosts'] = ['gitlab.example.com']
          #   - name: GITLAB_OMNIBUS_CONFIG
          #     value: |
          #       postgresql['enable'] = false
          #       gitlab_rails['db_username'] = "gitlab"
          #       gitlab_rails['db_password'] = "gitlab"
          #       gitlab_rails['db_host'] = "postgresql"
          #       gitlab_rails['db_port'] = "5432"
          #       gitlab_rails['db_database'] = "gitlabhq_production"
          #       gitlab_rails['db_adapter'] = 'postgresql'
          #       gitlab_rails['db_encoding'] = 'utf8'
          #       redis['enable'] = false
          #       gitlab_rails['redis_host'] = 'redis'
          #       gitlab_rails['redis_port'] = '6379'
          #       gitlab_rails['gitlab_shell_ssh_port'] = 30022
          #       external_url 'http://gitlab.example.com:30080'
          ports:
            - name: gitlab-http
              containerPort: 80
            - name: gitlab-https
              containerPort: 443
            - name: gitlab-ssh
              containerPort: 22
          volumeMounts:
            - mountPath: "/etc/gitlab"
              name: gitlab-etc
            - mountPath: "/var/opt/gitlab"
              name: gitlab-var-opt
      volumes:
        - name: gitlab-etc
          persistentVolumeClaim:
            claimName: gitlab-etc
        - name: gitlab-var-opt
          persistentVolumeClaim:
            claimName: gitlab-var-opt
